@startuml

!include ../../../commons.style
skinparam ranksep 50


class Client

interface Subject {
  + {abstract} operation()
}

Client .> Subject

class RealSubject {
  + operation()
}

Subject <|.. RealSubject

class Proxy {
  + this(Subject)
  __
  + operation()
}
Subject <|.. Proxy

RealSubject "1\ntarget" <- Proxy

@enduml
