# Travis continuous integration descriptor
# Author: Sebastien Mosser

language: java

jdk:
  - openjdk11

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - mvn -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V install

script:
  - mvn clean package
