@startuml

!include ../../../commons.style
skinparam ranksep 50

abstract class AbstractAlgorithm {
  + process()
  __
  ~ step1()
  ~ {abstract} operation()
  ~ step3()
}

class ConcreteAlgorithm {
  ~  operation()
}

AbstractAlgorithm <|-- ConcreteAlgorithm

@enduml
