@startuml

skinparam nodesep 75
skinparam ranksep 50
hide empty members

abstract class AbstractAlgorithm {
  + process()
  __
  ~ step1()
  ~ {abstract} operation()
  ~ step3()
}

class ConcreteAlgorithm {
  ~  operation()
}

AbstractAlgorithm <|-- ConcreteAlgorithm

@enduml
