@startuml

!include ../../../commons.style
skinparam nodesep 75


class Student <<Prototype>> {
  - Set<String> courses
  - String name
  __
  + this()
  - this(Student)
  __
  + <<clone>> duplicate(): Student
  + setName(String)
  + registerTo(String)
}

@enduml
