@startuml

!include ../../../commons.style
skinparam ranksep 50


class Client

interface Component {
  + {abstract} operation()
}

Client -> Component

class Leaf {
  + operation()
}
Component <|.. Leaf

class Composite {
  + operation()
  __
  + add(Component)
  + remove(Component)
}
Component <|.. Composite
Composite *--> "1..n\nchildren" Component

@enduml
