@startuml

!include ../../../commons.style

skinparam ranksep 50

class Director {
  + construct(): Product
}

Director *-> "1\nbuilder" Builder

interface Builder {
  + {abstract} buildPart()
  + {abstract} result(): Product
}

class ConcreteBuilder {
  + buildPart()
  + result(): Product
}

class Product

Builder <|.. ConcreteBuilder
Builder . Product

@enduml
