@startuml

!include ../../../commons.style

skinparam nodesep 100

interface Subject {
  + attach(o: Observer)
  + detach(o: Observer)
  + notify()
}

interface Observer {
  + {abstract} update()
}

Subject . Observer

class ConcreteSubject {

}

Subject <|.. ConcreteSubject

class ConcreteObserver {

}

Observer <|.. ConcreteObserver
ConcreteSubject *-> "n\nobservers" ConcreteObserver
ConcreteSubject "1\nobservee"<- ConcreteObserver

@enduml
