@startuml

skinparam nodesep 75
skinparam ranksep 50
hide empty members

interface Visitor {
  + {abstract} visitA(ConcreteElementA)
  + {abstract} visitB(ConcreteElementB)
}

class ConcreteVisitor {
  + visitA(ConcreteElementA)
  + visitB(ConcreteElementB)
}

Visitor <|.. ConcreteVisitor

interface Visitable {
  + {abstract} accept(Visitor)
}

Visitable . Visitor

class ConcreteElementA {
  + accept(Visitor)
  __
  + operationA()
}
Visitable <|.. ConcreteElementA

class ConcreteElementB {
  + accept(Visitor)
  __
  + operationB()
}
Visitable <|.. ConcreteElementB

@enduml
